// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! REST adapter: router assembly and cross-cutting middleware.
//!
//! Each endpoint module builds its own [`OpenApiRouter`], and [`build_router`] merges them, splits the result
//! into an Axum router plus the generated OpenAPI document, and wraps the router in the middleware defined
//! here.
//!
//! The middleware applies two per-request input-validation bounds — a maximum body size (413) and the
//! per-request deadline (504) — and assigns the request identity, deadline, and cancellation signal that
//! [`RequestContext`] carries into the backend.

pub mod clusters;
pub(crate) mod codec;
pub mod datatype;
pub mod ddl;
pub mod health;
pub mod metadata;
pub mod openapi;
pub mod pagination;
pub mod records;

use crate::backend::context::RequestContext;
use crate::backend::types::ClusterId;
use crate::backend::{FlussBackend, unknown_cluster};
#[cfg(test)]
use crate::config::REST_RESPONSE_GRACE;
use crate::config::{RequestLimitsConfig, RestServerConfig, rest_handler_timeout};
use crate::error::{ErrorEnvelope, ErrorKind, GatewayError, GatewayResult, panic_message};
use crate::lifecycle::Readiness;
use crate::observability;
use axum::Router;
use axum::body::{Body, Bytes};
use axum::extract::{DefaultBodyLimit, FromRequest, MatchedPath, Request};
use axum::http::{HeaderMap, HeaderValue, Method, StatusCode, Uri, header};
use axum::middleware::{self, Next};
use axum::response::{IntoResponse, Response};
use futures_util::FutureExt;
use serde::Serialize;
use serde::de::DeserializeOwned;
use std::net::SocketAddr;
use std::panic::AssertUnwindSafe;
use std::sync::{Arc, OnceLock};
use std::time::{Duration, Instant};
use tokio::sync::Semaphore;
use tokio_util::sync::CancellationToken;
use utoipa_axum::router::OpenApiRouter;

/// The deadline handed to a request whose configured timeout cannot be added to the current instant.
///
/// Only reachable if a duration slips past configuration validation; one hour keeps such a request bounded.
const MAX_REQUEST_DEADLINE: Duration = Duration::from_secs(3600);

/// Shared state for REST handlers.
///
/// Everything here is either immutable configuration or a shared process service. Nothing is scoped to a
/// request, a session, or a client.
#[derive(Clone)]
pub struct RestState {
    /// The gateway's single backend dependency: it answers cluster discovery, validates the cluster a
    /// request names, and serves every cluster-scoped operation.
    pub backend: Arc<dyn FlussBackend>,
    pub readiness: Arc<Readiness>,
    pub bind_address: SocketAddr,
    pub started_at: Instant,
    /// The OpenAPI document generated from the router this state was installed into.
    ///
    /// [`build_router`] fills it once, after the route modules are merged and split, so the served document is
    /// exactly the contract of the routes that are actually mounted.
    pub openapi: Arc<OnceLock<serde_json::Value>>,
    /// The row decoders of the write path, shared by every request.
    pub(crate) schemas: Arc<records::SchemaCache>,
    /// The write endpoint's optional rate limit.
    pub(crate) write_rate: Arc<records::RateLimit>,
    /// Rows per write request, beyond which the request is refused.
    pub write_max_rows: u32,
}

/// Per-request identifier, generated by the outermost middleware and echoed in the `x-request-id` response header and
/// error envelopes.
#[derive(Clone, Debug)]
pub struct RequestId(Arc<str>);

impl RequestId {
    /// The value echoed in the `x-request-id` header, or `unknown` when no middleware assigned one.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for RequestId {
    fn default() -> Self {
        Self(Arc::from("unknown"))
    }
}

/// Absolute request deadline assigned by the same middleware that enforces it.
#[derive(Clone, Copy, Debug)]
pub struct RequestDeadline(Instant);

impl RequestDeadline {
    pub fn instant(self) -> Instant {
        self.0
    }
}

/// Cancellation signal for the work of one request.
///
/// The middleware that inserts it holds the token's drop guard, so a request future that is dropped —
/// the caller disconnected, the deadline layer gave up, shutdown aborted the connection — cancels the
/// backend work instead of leaving it to notice on its own.
#[derive(Clone, Debug)]
pub struct RequestCancellation(CancellationToken);

/// Middleware and write limits extracted from the validated configuration.
#[derive(Debug, Clone)]
pub struct RestOptions {
    pub request_timeout: Duration,
    pub max_body_bytes: u64,
    pub metadata_max_concurrent_requests: u32,
    pub write_max_rows: u32,
    pub write_max_concurrent_requests: u32,
    pub write_rate_limit_enabled: bool,
    pub write_rate_limit_requests_per_second: u32,
    pub write_rate_limit_bytes_per_second: u64,
}

impl RestOptions {
    fn from_config(rest: &RestServerConfig, limits: &RequestLimitsConfig) -> Self {
        Self {
            request_timeout: rest.request_timeout.get(),
            max_body_bytes: rest.max_body_bytes.bytes(),
            metadata_max_concurrent_requests: rest.metadata_max_concurrent_requests,
            write_max_rows: limits.write_max_rows,
            write_max_concurrent_requests: limits.write_max_concurrent_requests,
            write_rate_limit_enabled: limits.write_rate_limit_enabled,
            write_rate_limit_requests_per_second: limits.write_rate_limit_requests_per_second,
            write_rate_limit_bytes_per_second: limits.write_rate_limit_bytes_per_second.bytes(),
        }
    }
}

/// Marks a response whose body is already in its final shape so the error-normalising middleware leaves it alone.
#[derive(Clone, Copy)]
struct ShapedResponse;

/// Renders the error envelope with the status its kind maps to, marks the response as already shaped, and adds
/// `Retry-After` where the taxonomy calls for it.
fn error_response(error: &GatewayError, request_id: &RequestId) -> Response {
    let status = StatusCode::from_u16(error.kind().http_status())
        .unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
    let mut response =
        json_response_with_status(status, &ErrorEnvelope::new(error, request_id.as_str()))
            .unwrap_or_else(|_| StatusCode::INTERNAL_SERVER_ERROR.into_response());
    response.extensions_mut().insert(ShapedResponse);
    if error.kind().retry_after() {
        response
            .headers_mut()
            .insert(header::RETRY_AFTER, HeaderValue::from_static("1"));
    }
    response
}

/// Serializes `value` as a 200 JSON response. Fails only when serialization fails, which is reported as internal.
fn json_response<T: Serialize>(value: &T) -> Result<Response, GatewayError> {
    json_response_with_status(StatusCode::OK, value)
}

/// Serializes `value` as a JSON response with the given status. Serialization failures are reported as internal.
fn json_response_with_status<T: Serialize>(
    status: StatusCode,
    value: &T,
) -> Result<Response, GatewayError> {
    let body = serde_json::to_vec(value).map_err(|error| {
        GatewayError::internal(format!("failed to serialize JSON response: {error}"))
    })?;
    let mut response = (status, Body::from(body)).into_response();
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );
    Ok(response)
}

/// Reads a size-limited request body and deserializes it as JSON.
async fn parse_json_body<T: DeserializeOwned>(mut request: Request) -> Result<T, GatewayError> {
    let headers = std::mem::take(request.headers_mut());
    let body = Bytes::from_request(request, &()).await.map_err(|error| {
        if error.status() == StatusCode::PAYLOAD_TOO_LARGE {
            GatewayError::limit_exceeded("request body exceeds the configured limit")
        } else {
            GatewayError::invalid_argument(format!("unreadable request body: {error}"))
        }
    })?;
    validate_json_content_type(&headers)?;
    serde_json::from_slice(&body)
        .map_err(|error| GatewayError::invalid_argument(format!("invalid JSON body: {error}")))
}

fn validate_json_content_type(headers: &HeaderMap) -> Result<(), GatewayError> {
    let Some(value) = headers.get(header::CONTENT_TYPE) else {
        return Err(GatewayError::new(
            crate::error::ErrorKind::UnsupportedMediaType,
            "Content-Type must be application/json or application/*+json",
        ));
    };
    let media_type = value
        .to_str()
        .map_err(|_| GatewayError::invalid_argument("unreadable Content-Type header"))?
        .split(';')
        .next()
        .unwrap_or_default()
        .trim()
        .to_ascii_lowercase();
    let supported = media_type == "application/json"
        || media_type
            .strip_prefix("application/")
            .is_some_and(|subtype| subtype.ends_with("+json"));
    if supported {
        Ok(())
    } else {
        Err(GatewayError::new(
            crate::error::ErrorKind::UnsupportedMediaType,
            "Content-Type must be application/json or application/*+json",
        ))
    }
}

/// The request ID the outermost middleware assigned, for a handler rendering its own envelope.
fn request_id(request: &Request) -> RequestId {
    request
        .extensions()
        .get::<RequestId>()
        .cloned()
        .unwrap_or_default()
}

/// Resolves a configured cluster and builds its backend request context.
fn resolve_cluster(
    state: &RestState,
    request: &Request,
    cluster: &str,
) -> GatewayResult<(Arc<dyn FlussBackend>, RequestContext)> {
    if !state.backend.has_cluster(cluster) {
        return Err(unknown_cluster(cluster));
    }
    let cluster = ClusterId::try_from(cluster).expect("the backend serves this cluster ID");
    Ok((state.backend.clone(), request_context(cluster, request)))
}

/// Builds the backend context of one cluster-scoped request from the middleware-assigned metadata.
///
/// The caller is anonymous until the authenticator lands; the deadline and the cancellation signal are
/// the ones the middleware also enforces, so a backend call cannot outlive its request.
fn request_context(cluster_id: ClusterId, request: &Request) -> RequestContext {
    let deadline = request
        .extensions()
        .get::<RequestDeadline>()
        .copied()
        .unwrap_or_else(|| deadline_from_now(MAX_REQUEST_DEADLINE));
    let cancellation = request
        .extensions()
        .get::<RequestCancellation>()
        .map_or_else(CancellationToken::new, |cancellation| {
            cancellation.0.clone()
        });
    RequestContext::new(
        Arc::from(request_id(request).as_str()),
        cluster_id,
        deadline.instant(),
        cancellation,
        None,
    )
}

/// Assembles the REST frontend from the REST configuration and the shared process services.
///
/// This is the frontend's entry point for the lifecycle: it owns how the handler state is built and
/// the router is wired, so the lifecycle stays protocol-agnostic and only supervises the listener
/// this router is served on. `local_addr` is the resolved bound address, which differs from the
/// configured one when the port is 0.
pub fn build(
    rest_config: &RestServerConfig,
    request_limits: &RequestLimitsConfig,
    backend: Arc<dyn FlussBackend>,
    readiness: &Arc<Readiness>,
    local_addr: SocketAddr,
) -> Router {
    let options = RestOptions::from_config(rest_config, request_limits);
    let state = RestState {
        backend,
        readiness: readiness.clone(),
        bind_address: local_addr,
        started_at: Instant::now(),
        openapi: Arc::new(OnceLock::new()),
        schemas: Arc::new(records::SchemaCache::new()),
        write_rate: Arc::new(records::RateLimit::from_config(
            options.write_rate_limit_enabled,
            options.write_rate_limit_requests_per_second,
            options.write_rate_limit_bytes_per_second,
        )),
        write_max_rows: options.write_max_rows,
    };
    build_router(state, &options)
}

/// Builds the router: the health routes (`GET /health` for liveness, `GET /ready` for readiness) sit
/// outside both the acceptance guard and the body/deadline budget so they answer while draining and
/// never carry a body; every guarded route (`/v1/openapi.json`, `/v1/clusters`, the metadata routes,
/// and later all data/control routes) carries the request-body size and deadline budget, with the
/// acceptance guard outermost so draining answers 503 without consuming bodies.
pub fn build_router(state: RestState, options: &RestOptions) -> Router {
    let (queryless_guarded, mut guarded_api) = OpenApiRouter::new()
        .merge(openapi::routes())
        .merge(clusters::routes())
        .split_for_parts();
    let (metadata_router, metadata_api) = OpenApiRouter::new()
        .merge(metadata::routes())
        .merge(ddl::routes())
        .split_for_parts();
    let (records_router, records_api) = OpenApiRouter::new()
        .merge(records::routes())
        .split_for_parts();
    let (open_router, open_api) = OpenApiRouter::new()
        .merge(health::routes())
        .split_for_parts();

    guarded_api.merge(metadata_api);
    guarded_api.merge(records_api);
    guarded_api.merge(open_api);
    let _ = state.openapi.set(openapi::finalize(guarded_api));

    let backend = state.backend.clone();
    let metadata_router = apply_concurrency_limit(
        metadata_router,
        options.metadata_max_concurrent_requests,
        "too many concurrent metadata requests",
    );
    let records_router = apply_concurrency_limit(
        records_router,
        options.write_max_concurrent_requests,
        "too many concurrent write requests",
    )
    .route_layer(middleware::from_fn(reject_query_parameters));
    let guarded_router = queryless_guarded
        .route_layer(middleware::from_fn(reject_query_parameters))
        .merge(metadata_router)
        .merge(records_router);
    // `apply_data_limits` also stamps the request deadline, so the guarded side needs no separate
    // `assign_request_deadline` layer.
    let guarded = apply_data_limits(guarded_router.with_state(state.clone()), options);
    let guarded = apply_acceptance_guard(guarded, state.readiness.clone());
    let open = open_router
        .route_layer(middleware::from_fn(reject_query_parameters))
        .fallback(unknown_route)
        .with_state(state)
        .layer(middleware::from_fn(assign_request_deadline(
            options.request_timeout,
        )));
    apply_common_middleware(open.merge(guarded), Some(backend))
}

/// Rejects query strings only on the route groups whose OpenAPI operations declare none.
async fn reject_query_parameters(request: Request, next: Next) -> Response {
    if request.uri().query().is_some() {
        return error_response(
            &GatewayError::invalid_argument("this operation does not accept query parameters"),
            &request_id(&request),
        );
    }
    next.run(request).await
}

/// Bounds one route group without queueing requests behind an overloaded backend.
fn apply_concurrency_limit<S>(
    router: Router<S>,
    max_requests: u32,
    message: &'static str,
) -> Router<S>
where
    S: Clone + Send + Sync + 'static,
{
    let permits = Arc::new(Semaphore::new(max_requests as usize));
    router.route_layer(middleware::from_fn(move |request: Request, next: Next| {
        let permits = permits.clone();
        async move {
            let Ok(_permit) = permits.try_acquire_owned() else {
                return error_response(
                    &GatewayError::resource_exhausted(message),
                    &request_id(&request),
                );
            };
            next.run(request).await
        }
    }))
}

/// Rejects new application work after graceful draining starts while keeping `GET /health` available.
fn apply_acceptance_guard(router: Router, readiness: Arc<Readiness>) -> Router {
    router.layer(middleware::from_fn(move |request: Request, next: Next| {
        let readiness = readiness.clone();
        async move {
            if let Err(error) = readiness.ensure_accepting() {
                return error_response(&error, &request_id(&request));
            }
            next.run(request).await
        }
    }))
}

/// Wraps a test router with the production middleware.
#[cfg(test)]
fn apply_middleware(router: Router, options: &RestOptions) -> Router {
    apply_common_middleware(apply_data_limits(router, options), None)
}

/// The deadline of a request starting now, ending [`REST_RESPONSE_GRACE`] before the middleware
/// timeout.
///
/// The checked additions are defence in depth — configuration caps every duration well below the
/// instant-arithmetic limit — and, like Envoy's `grpc_timeout_offset`, the grace applies only when
/// the timeout is longer than it.
fn deadline_from_now(request_timeout: Duration) -> RequestDeadline {
    let handler_budget = rest_handler_timeout(request_timeout);
    let now = Instant::now();
    RequestDeadline(
        now.checked_add(handler_budget)
            .or_else(|| now.checked_add(MAX_REQUEST_DEADLINE))
            .unwrap_or(now),
    )
}

/// Records the absolute deadline of a request that does not pass through the data-limit layer.
fn assign_request_deadline(
    request_timeout: Duration,
) -> impl Fn(Request, Next) -> std::pin::Pin<Box<dyn Future<Output = Response> + Send>> + Clone {
    move |mut request: Request, next: Next| {
        Box::pin(async move {
            request
                .extensions_mut()
                .insert(deadline_from_now(request_timeout));
            next.run(request).await
        })
    }
}

fn apply_data_limits(router: Router, options: &RestOptions) -> Router {
    let request_timeout = options.request_timeout;
    let max_body_bytes = options.max_body_bytes;

    let limits = move |mut request: Request, next: Next| async move {
        let request_id = request_id(&request);
        request
            .extensions_mut()
            .insert(deadline_from_now(request_timeout));
        // The guard lives in this future, so whatever drops the request — the timeout below, a
        // disconnected caller, an aborted connection during shutdown — cancels the handler's work.
        let cancellation = CancellationToken::new();
        request
            .extensions_mut()
            .insert(RequestCancellation(cancellation.clone()));
        let _cancel_on_drop = cancellation.drop_guard();

        let oversized = declared_content_length(&request).filter(|length| *length > max_body_bytes);
        if let Some(length) = oversized {
            log::warn!(
                "request_id={} rejecting body of {} bytes above {} bytes",
                request_id.as_str(),
                length,
                max_body_bytes
            );
            return error_response(
                &GatewayError::limit_exceeded(format!(
                    "request body of {length} bytes exceeds the limit of {max_body_bytes} bytes"
                )),
                &request_id,
            );
        }

        // Rejections are not counted separately: they leave through the access-log layer above, which
        // records them in `fluss_gateway_rest_requests_total` under their status code.
        let result = tokio::time::timeout(request_timeout, next.run(request)).await;
        match result {
            Ok(response) => response,
            Err(_) => {
                log::warn!(
                    "request_id={} deadline exceeded after {:?}",
                    request_id.as_str(),
                    request_timeout
                );
                error_response(
                    &GatewayError::deadline_exceeded("request deadline exceeded"),
                    &request_id,
                )
            }
        }
    };

    router
        .layer(DefaultBodyLimit::max(
            usize::try_from(max_body_bytes).unwrap_or(usize::MAX),
        ))
        .layer(middleware::from_fn(limits))
}

fn apply_common_middleware(router: Router, backend: Option<Arc<dyn FlussBackend>>) -> Router {
    router
        .layer(middleware::from_fn(catch_panic))
        .layer(middleware::from_fn(request_log(backend)))
        .layer(middleware::from_fn(request_context_id))
}

/// Turns a panic below this layer into the error envelope a client is promised.
///
/// Sitting inside the access-log layer, the synthesised 500 is logged and counted like any other
/// response, where a dropped connection would have been recorded nowhere. The payload goes to the
/// log, never into the response, since it can carry internal detail.
async fn catch_panic(request: Request, next: Next) -> Response {
    let request_id = request_id(&request);
    match AssertUnwindSafe(next.run(request)).catch_unwind().await {
        Ok(response) => response,
        Err(payload) => {
            log::error!(
                "request_id={} handler panicked: {}",
                request_id.as_str(),
                panic_message(payload)
            );
            error_response(&GatewayError::internal("internal error"), &request_id)
        }
    }
}

/// Logs and counts one completed request.
///
/// Metrics use the bounded matched `route`; only the access log includes the concrete `path`.
///
/// The `cluster` label stays bounded: a route without a `{cluster}` segment reports `none`, and a
/// segment that names no configured cluster reports `unknown`, so a caller-supplied value can never
/// become a label value.
fn request_log(
    backend: Option<Arc<dyn FlussBackend>>,
) -> impl Fn(Request, Next) -> std::pin::Pin<Box<dyn Future<Output = Response> + Send>> + Clone {
    move |request: Request, next: Next| {
        let backend = backend.clone();
        Box::pin(async move {
            let started = Instant::now();
            let method = request.method().clone();
            let path = request.uri().path().to_string();
            let route = request
                .extensions()
                .get::<MatchedPath>()
                .map(MatchedPath::as_str)
                .unwrap_or("<unmatched>")
                .to_string();
            let cluster = cluster_label(backend.as_deref(), &route, &path).to_string();
            let request_id = request_id(&request);
            let response = next.run(request).await;
            let elapsed = started.elapsed();
            let status = response.status();
            observability::http_request(
                &cluster,
                method.as_str(),
                &route,
                status.as_u16(),
                elapsed,
            );
            log::debug!(
                "{}",
                format_request_log(
                    &method,
                    &route,
                    &path,
                    &request_id,
                    status,
                    elapsed.as_millis(),
                )
            );
            response
        })
    }
}

/// The bounded `cluster` label of one request: a configured ID, `unknown`, or `none`.
fn cluster_label<'a>(backend: Option<&dyn FlussBackend>, route: &str, path: &'a str) -> &'a str {
    let Some(position) = route
        .split('/')
        .position(|segment| segment == "{cluster}")
        .filter(|_| backend.is_some())
    else {
        return "none";
    };
    path.split('/')
        .nth(position)
        .filter(|candidate| backend.is_some_and(|backend| backend.has_cluster(candidate)))
        .unwrap_or("unknown")
}

fn format_request_log(
    method: &Method,
    route: &str,
    path: &str,
    request_id: &RequestId,
    status: StatusCode,
    elapsed_ms: u128,
) -> String {
    format!(
        "method={method} route={route} path={path} request_id={} status={} elapsed_ms={elapsed_ms}",
        request_id.as_str(),
        status.as_u16()
    )
}

async fn request_context_id(mut request: Request, next: Next) -> Response {
    let request_id = RequestId(Arc::from(uuid::Uuid::new_v4().to_string()));
    request.extensions_mut().insert(request_id.clone());

    let response = next.run(request).await;
    let mut response = normalize_error(response, &request_id);

    if let Ok(value) = HeaderValue::from_str(request_id.as_str()) {
        response.headers_mut().insert("x-request-id", value);
    }
    response
}

/// Classifies a status the framework produced on its own — a rejected extractor, a route that exists for
/// another method — so it can be answered with the same envelope as a handler failure.
fn framework_error_kind(status: StatusCode) -> ErrorKind {
    match status.as_u16() {
        400 | 422 => ErrorKind::InvalidArgument,
        404 => ErrorKind::NotFound,
        405 => ErrorKind::MethodNotAllowed,
        406 => ErrorKind::NotAcceptable,
        408 | 504 => ErrorKind::DeadlineExceeded,
        413 => ErrorKind::LimitExceeded,
        415 => ErrorKind::UnsupportedMediaType,
        429 => ErrorKind::ResourceExhausted,
        501 => ErrorKind::Unsupported,
        503 => ErrorKind::Unavailable,
        server_error if server_error >= 500 => ErrorKind::Internal,
        _ => ErrorKind::InvalidArgument,
    }
}

/// The reason phrase of the status a kind maps to, so this layer keeps no message table of its own.
fn framework_error_message(kind: ErrorKind) -> &'static str {
    StatusCode::from_u16(kind.http_status())
        .ok()
        .and_then(|status| status.canonical_reason())
        .unwrap_or("request failed")
}

fn normalize_error(response: Response, request_id: &RequestId) -> Response {
    let status = response.status();
    if !(status.is_client_error() || status.is_server_error()) {
        return response;
    }
    if response.extensions().get::<ShapedResponse>().is_some() {
        return response;
    }

    let kind = framework_error_kind(status);
    error_response(
        &GatewayError::new(kind, framework_error_message(kind)),
        request_id,
    )
}

async fn unknown_route(method: Method, uri: Uri, request: Request) -> Response {
    let request_id = request_id(&request);
    error_response(
        &GatewayError::not_found(format!("no route for {method} {}", uri.path())),
        &request_id,
    )
}

fn declared_content_length(request: &Request) -> Option<u64> {
    request
        .headers()
        .get(header::CONTENT_LENGTH)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.parse().ok())
}

#[cfg(test)]
pub mod test_support {
    //! Router and state builders shared by the in-crate protocol tests.

    use super::*;

    /// Middleware options with short, test-friendly bounds.
    pub fn test_options() -> RestOptions {
        RestOptions {
            request_timeout: Duration::from_secs(5),
            max_body_bytes: 1024,
            metadata_max_concurrent_requests: 16,
            write_max_rows: 10_000,
            write_max_concurrent_requests: 64,
            write_rate_limit_enabled: false,
            write_rate_limit_requests_per_second: 1000,
            write_rate_limit_bytes_per_second: 64 * 1024 * 1024,
        }
    }

    /// Builds handler state over a fresh readiness gate, which starts neither serving nor draining.
    pub fn test_state() -> RestState {
        state_with_backend(Arc::new(crate::backend::fake::FakeFlussBackend::new()))
    }

    /// Builds handler state over one backend fixture.
    pub fn state_with_backend(backend: Arc<dyn FlussBackend>) -> RestState {
        state_with_backend_and_options(backend, &test_options())
    }

    pub fn state_with_backend_and_options(
        backend: Arc<dyn FlussBackend>,
        options: &RestOptions,
    ) -> RestState {
        RestState {
            backend,
            readiness: Arc::new(Readiness::new()),
            bind_address: "127.0.0.1:0".parse().expect("valid"),
            started_at: Instant::now(),
            openapi: Arc::new(OnceLock::new()),
            schemas: Arc::new(records::SchemaCache::new()),
            write_rate: Arc::new(records::RateLimit::from_config(
                options.write_rate_limit_enabled,
                options.write_rate_limit_requests_per_second,
                options.write_rate_limit_bytes_per_second,
            )),
            write_max_rows: options.write_max_rows,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::routing::get;
    use http_body_util::BodyExt;
    use serde::Deserialize;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use tower::ServiceExt;

    #[derive(Debug, Deserialize, PartialEq)]
    #[serde(deny_unknown_fields)]
    struct BodyFixture {
        value: u32,
    }

    async fn body_json(response: Response) -> serde_json::Value {
        let bytes = response
            .into_body()
            .collect()
            .await
            .expect("body")
            .to_bytes();
        serde_json::from_slice(&bytes).expect("json body")
    }

    #[tokio::test]
    async fn shared_json_parser_enforces_media_type_and_serde_strictness() {
        for (content_type, expected) in [
            (None, Err(ErrorKind::UnsupportedMediaType)),
            (Some("text/plain"), Err(ErrorKind::UnsupportedMediaType)),
            (Some("application/json"), Ok(BodyFixture { value: 7 })),
            (
                Some("application/vnd.fluss+json; charset=utf-8"),
                Ok(BodyFixture { value: 7 }),
            ),
        ] {
            let mut request = Request::builder();
            if let Some(content_type) = content_type {
                request = request.header(header::CONTENT_TYPE, content_type);
            }
            let request = request.body(Body::from(r#"{"value": 7}"#)).unwrap();
            let result = parse_json_body::<BodyFixture>(request)
                .await
                .map_err(|error| error.kind());
            assert_eq!(result, expected, "{content_type:?}");
        }
        for body in [
            r#"{"value": 7, "unknown": true}"#,
            r#"{"value": 7, "value": 8}"#,
            r#"{"value":"#,
            "",
        ] {
            let request = Request::builder()
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(body))
                .unwrap();
            let error = parse_json_body::<BodyFixture>(request).await.unwrap_err();
            assert_eq!(error.kind(), ErrorKind::InvalidArgument, "{body}");
        }

        let stream =
            futures_util::stream::iter([Err::<Bytes, _>(std::io::Error::other("read failed"))]);
        let error = parse_json_body::<BodyFixture>(Request::new(Body::from_stream(stream)))
            .await
            .unwrap_err();
        assert_eq!(error.kind(), ErrorKind::InvalidArgument);
        assert!(error.message().starts_with("unreadable request body:"));
    }

    #[tokio::test]
    async fn unknown_route_yields_404_envelope() {
        let app = build_router(test_support::test_state(), &test_support::test_options());
        for path in ["/nope", "/nope?unknown=value"] {
            let response = app
                .clone()
                .oneshot(Request::builder().uri(path).body(Body::empty()).unwrap())
                .await
                .unwrap();

            assert_eq!(response.status(), StatusCode::NOT_FOUND, "{path}");
            let header_id = response
                .headers()
                .get("x-request-id")
                .and_then(|v| v.to_str().ok())
                .map(str::to_string)
                .expect("x-request-id header");

            let json = body_json(response).await;
            assert_eq!(json["error"]["code"], "not_found", "{path}");
            assert_eq!(json["error"]["request_id"], header_id.as_str(), "{path}");
            assert!(
                json["error"]["message"].as_str().unwrap().contains("/nope"),
                "message names the missing route: {json}"
            );
        }
    }

    #[tokio::test]
    async fn oversized_body_yields_413_envelope() {
        let state = test_support::test_state();
        state.readiness.set_serving();
        let app = build_router(state, &test_support::test_options());
        for (method, path) in [
            (Method::POST, "/v1/clusters/default/databases"),
            (
                Method::GET,
                "/v1/clusters/default/databases/sales/tables/orders",
            ),
            (
                Method::DELETE,
                "/v1/clusters/default/databases/sales/tables/orders",
            ),
        ] {
            let response = app
                .clone()
                .oneshot(
                    Request::builder()
                        .method(method.clone())
                        .uri(path)
                        .header(header::CONTENT_LENGTH, "1048576")
                        .body(Body::empty())
                        .unwrap(),
                )
                .await
                .unwrap();

            assert_eq!(response.status(), StatusCode::PAYLOAD_TOO_LARGE, "{method}");
            let json = body_json(response).await;
            assert_eq!(json["error"]["code"], "limit_exceeded", "{method}");
            assert!(json["error"]["request_id"].as_str().is_some(), "{method}");
        }
    }

    #[tokio::test]
    async fn request_timeout_yields_504_envelope() {
        /// Runs longer than the configured test request deadline.
        async fn slow() -> &'static str {
            tokio::time::sleep(Duration::from_millis(250)).await;
            "ok"
        }
        let mut options = test_support::test_options();
        options.request_timeout = Duration::from_millis(50);
        let app = apply_middleware(Router::new().route("/slow", get(slow)), &options);

        let response = app
            .oneshot(Request::builder().uri("/slow").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::GATEWAY_TIMEOUT);
        let json = body_json(response).await;
        assert_eq!(json["error"]["code"], "timeout");
    }

    /// The deadline reserves the response grace, except for timeouts that are not longer than it,
    /// which keep their full budget.
    #[test]
    fn the_deadline_reserves_the_response_grace_when_the_timeout_allows_it() {
        for (timeout, budget) in [
            (
                Duration::from_secs(30),
                Duration::from_secs(30) - REST_RESPONSE_GRACE,
            ),
            (REST_RESPONSE_GRACE, REST_RESPONSE_GRACE),
            (Duration::from_millis(200), Duration::from_millis(200)),
        ] {
            let before = Instant::now();
            let deadline = deadline_from_now(timeout).instant();
            let after = Instant::now();

            assert!(deadline >= before + budget, "timeout={timeout:?}");
            assert!(
                deadline <= after + budget + Duration::from_millis(50),
                "timeout={timeout:?}"
            );
        }
    }

    /// A handler that finishes exactly at its deadline still gets its response out: the middleware
    /// timeout backstops the deadline plus the response grace instead of racing it.
    #[tokio::test]
    async fn response_completing_at_the_deadline_is_delivered() {
        async fn finishes_at_deadline(request: Request) -> &'static str {
            let deadline = request
                .extensions()
                .get::<RequestDeadline>()
                .copied()
                .expect("the limits middleware assigns the deadline");
            tokio::time::sleep_until(tokio::time::Instant::from_std(deadline.instant())).await;
            "ok"
        }
        let mut options = test_support::test_options();
        options.request_timeout = REST_RESPONSE_GRACE + Duration::from_millis(400);
        let app = apply_middleware(
            Router::new().route("/deadline", get(finishes_at_deadline)),
            &options,
        );

        let response = app
            .oneshot(
                Request::builder()
                    .uri("/deadline")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
    }

    /// A route that exists for another method answers the shared envelope with a code the published
    /// vocabulary contains.
    #[tokio::test]
    async fn wrong_method_yields_a_405_envelope() {
        let app = build_router(test_support::test_state(), &test_support::test_options());
        let response = app
            .oneshot(
                Request::builder()
                    .method(Method::POST)
                    .uri("/health")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::METHOD_NOT_ALLOWED);
        let json = body_json(response).await;
        assert_eq!(json["error"]["code"], "method_not_allowed");
        assert!(
            crate::error::wire_codes().contains(&"method_not_allowed"),
            "the published vocabulary declares every code the gateway emits"
        );
    }

    #[tokio::test]
    async fn generic_middleware_does_not_impose_a_global_concurrency_limit() {
        /// Holds a request open long enough for several to overlap.
        async fn slow() -> &'static str {
            tokio::time::sleep(Duration::from_millis(50)).await;
            "ok"
        }
        let app = apply_middleware(
            Router::new().route("/slow", get(slow)),
            &test_support::test_options(),
        );
        let request = || Request::builder().uri("/slow").body(Body::empty()).unwrap();

        let responses =
            futures_util::future::join_all((0..16).map(|_| app.clone().oneshot(request()))).await;

        for response in responses {
            assert_eq!(response.unwrap().status(), StatusCode::OK);
        }
    }

    #[tokio::test]
    async fn metadata_concurrency_rejects_without_queueing_and_releases_its_permit() {
        let entered = Arc::new(tokio::sync::Notify::new());
        let release = Arc::new(tokio::sync::Notify::new());
        let calls = Arc::new(AtomicUsize::new(0));
        let handler = {
            let entered = entered.clone();
            let release = release.clone();
            let calls = calls.clone();
            move || {
                let entered = entered.clone();
                let release = release.clone();
                let calls = calls.clone();
                async move {
                    if calls.fetch_add(1, Ordering::SeqCst) == 0 {
                        entered.notify_one();
                        release.notified().await;
                    }
                    "ok"
                }
            }
        };
        let app = apply_common_middleware(
            apply_concurrency_limit(
                Router::new().route("/metadata", get(handler)),
                1,
                "too many concurrent metadata requests",
            ),
            None,
        );
        let request = || {
            Request::builder()
                .uri("/metadata")
                .body(Body::empty())
                .unwrap()
        };

        let first = tokio::spawn(app.clone().oneshot(request()));
        entered.notified().await;

        let rejected = app.clone().oneshot(request()).await.unwrap();
        assert_eq!(rejected.status(), StatusCode::TOO_MANY_REQUESTS);
        assert_eq!(rejected.headers()[header::RETRY_AFTER], "1");
        assert_eq!(
            body_json(rejected).await["error"]["code"],
            "resource_exhausted"
        );
        assert_eq!(calls.load(Ordering::SeqCst), 1);

        release.notify_one();
        assert_eq!(first.await.unwrap().unwrap().status(), StatusCode::OK);
        assert_eq!(
            app.oneshot(request()).await.unwrap().status(),
            StatusCode::OK
        );
        assert_eq!(calls.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn success_responses_carry_request_id_header() {
        let app = build_router(test_support::test_state(), &test_support::test_options());
        let response = app
            .oneshot(
                Request::builder()
                    .uri("/health")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        assert!(response.headers().contains_key("x-request-id"));
    }

    /// A panicking handler answers the shared envelope instead of dropping the connection.
    #[tokio::test]
    async fn a_panicking_handler_yields_a_500_envelope() {
        async fn boom() -> &'static str {
            panic!("handler bug");
        }
        let app = apply_middleware(
            Router::new().route("/boom", get(boom)),
            &test_support::test_options(),
        );

        // The default panic hook still prints the payload; that output is expected here.
        let response = app
            .oneshot(Request::builder().uri("/boom").body(Body::empty()).unwrap())
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::INTERNAL_SERVER_ERROR);
        let request_id = response
            .headers()
            .get("x-request-id")
            .and_then(|value| value.to_str().ok())
            .map(str::to_string)
            .expect("x-request-id header");
        let json = body_json(response).await;
        assert_eq!(json["error"]["code"], "internal");
        assert_eq!(json["error"]["request_id"], request_id.as_str());
        assert!(
            !json["error"]["message"]
                .as_str()
                .unwrap()
                .contains("handler bug"),
            "the panic payload stays in the log, never in the response: {json}"
        );
    }

    /// The `cluster` metric label stays inside its bounded vocabulary: a configured ID, `unknown` for
    /// anything else a caller can put in the path, and `none` for a route without a cluster segment.
    #[test]
    fn the_cluster_metric_label_never_carries_a_caller_supplied_value() {
        let backend = crate::backend::fake::FakeFlussBackend::new();
        let route = "/v1/clusters/{cluster}/databases";

        assert_eq!(
            cluster_label(Some(&backend), route, "/v1/clusters/default/databases"),
            "default"
        );
        for path in [
            "/v1/clusters/other/databases",
            "/v1/clusters/Not%20A%20Cluster/databases",
            "/v1/clusters",
        ] {
            assert_eq!(
                cluster_label(Some(&backend), route, path),
                "unknown",
                "{path}"
            );
        }
        assert_eq!(
            cluster_label(Some(&backend), "/v1/clusters", "/v1/clusters"),
            "none"
        );
        assert_eq!(
            cluster_label(None, route, "/v1/clusters/default/databases"),
            "none"
        );
    }

    #[test]
    fn request_log_contains_route_and_path_context() {
        let message = format_request_log(
            &Method::POST,
            "/v1/clusters/{cluster}/databases",
            "/v1/clusters/default/databases",
            &RequestId(Arc::from("request-7")),
            StatusCode::CREATED,
            23,
        );
        assert_eq!(
            message,
            "method=POST route=/v1/clusters/{cluster}/databases path=/v1/clusters/default/databases request_id=request-7 status=201 elapsed_ms=23"
        );
    }
}
